[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true  # ← This fixes the stack too deep error

[profile.default.model_checker]
contracts = {}

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/EtP7XG5-_2JXN1IlArbeeZpYQ8yWK3O5"
